export const GET_TICKETS_REQUEST = 'GET_TICKETS_REQUEST';
export const GET_TICKETS_SUCCESS = 'GET_TICKETS_SUCCESS';
export const GET_TICKETS_FAILED = 'GET_TICKETS_FAILED';
export const SORTING_PRICE = 'SORTING_PRICE';
export const SORTING_DURATION = 'SORTING_DURATION';
