export const GET_TICKETS_SUCCESS = 'GET_TICKETS_SUCCESS';
export const GET_TICKETS_FAILED = 'GET_TICKETS_FAILED';
export const SORTING_PRICE = 'SORTING_PRICE';
export const SORTING_DURATION = 'SORTING_DURATION';
export const NEXT_PAGE = 'NEXT_PAGE';
export const SET_FETCHING = 'SET_FETCHING';
export const DEL_FETCHING = 'DEL_FETCHING';
